

### GET all rolls
GET http://localhost:5000 HTTP/1.1


### POST register route - make tester-bob 
POST http://localhost:5000/login/register
content-type: application/json

{
    "username":"Dunc",
    "email": "Dunc@gmail.com",
    "password": "123456"
}

### POST auth route - tester-bob login 
POST http://localhost:5000/login/login
content-type: application/json

{
    "username":"Dunc",
    "password": "123456"
}

### POST subscription route - tester-osco login 
POST http://localhost:5000/order
content-type: application/json
Cookie: connect.sid=s%3AEC-DlFtveuvq7QIEgXEZ9_92C3bKYDYJ.GEb5NTplTey1KZU6wSHMCt1Kv%2BTb4zYq%2BiaQ1BZxsWw


{
    "name":"Softy",
    "address": "myAddress",
    "rolls": "5ecf27f6f36522b5d0e8a816",
    "subscription": "5ecf9b5cfa9974108ccf378d"
}


